version: '3'

services:
  belvo-web:
    container_name: belvo-http
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ../drf_src:/drf_src
