# Generated by Django 2.2.11 on 2020-03-27 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
