# Generated by Django 2.2.11 on 2020-03-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20200327_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('inflow', 'inflow'), ('outflow', 'outflow')], default='inflow', max_length=32),
        ),
    ]
